development:
  adapter: postgresql
  encoding: unicode
  database: art_gallery_development
  pool: 5
  username:
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: art_gallery_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: art_gallery_production
  pool: 5
  username:
  password:
